Fixed regex validation for puppet 4 and 5
Some parameters needs to be as a string, becuase puppet is raising
error: "Error while evaluating a Function Call, validate_re():
input needs to be a String, not a Fixnum"